Revert "Merge pull request #9902 from NixOS/require-fixed-output-fetchurl"
This is not actually a bug on Nix (version 2.18, at least), and breaks code
I've written (with no other way to write that code.)

    nix-repl> :b builtins.derivation { name = "nix-cache-info"; system = "x86_64-linux"; builder = "builtin:fetchurl"; url = https://cache.nixos.org/nix-cache-info; outputHashMode = "flat"; }
    warning: error: unable to download 'https://cache.nixos.org/nix-cache-info': Couldn't resolve host name (6); retrying in 309 ms
    warning: error: unable to download 'https://cache.nixos.org/nix-cache-info': Couldn't resolve host name (6); retrying in 607 ms
    warning: error: unable to download 'https://cache.nixos.org/nix-cache-info': Couldn't resolve host name (6); retrying in 1002 ms
    warning: error: unable to download 'https://cache.nixos.org/nix-cache-info': Couldn't resolve host name (6); retrying in 2554 ms
    error: builder for '/nix/store/z89j6fdfm6k9k1qir99449wyvldpm2ma-nix-cache-info.drv' failed with exit code 1;
           last 4 log lines:
           > error:
           >        … writing file '/nix/store/l9ax62fdagg4cvw9wd4h84cf4pxqcmlg-nix-cache-info'
           >
           >        error: unable to download 'https://cache.nixos.org/nix-cache-info': Couldn't resolve host name (6)
           For full logs, run 'nix-store -l /nix/store/z89j6fdfm6k9k1qir99449wyvldpm2ma-nix-cache-info.drv'.

This reverts commit 081dc5daa1e9047e693d496a5cdf77c0a4d717ba, reversing
changes made to ef6d055ace0c3ccc1955ddf2150024ff9d58f2bd.