libstore: fix buffer resize in `addToStoreFromDump`
The original issue I'm aiming to solve were hash-mismatches on
remote-builds like this:

    this derivation will be built:
      /nix/store/2nwv1fm5bs0a2sgb2a014gv7hgfaj3f7-ruby2.7.4-vagrant_cloud-3.0.5.drv
    building '/nix/store/2nwv1fm5bs0a2sgb2a014gv7hgfaj3f7-ruby2.7.4-vagrant_cloud-3.0.5.drv' on 'ssh-ng://builder-ng'...
    copying 1 paths...
    copying path '/nix/store/j3wsx0in5hgnl3sr91i8h19b74w5hcz5-vagrant_cloud-3.0.5.gem' to 'ssh-ng://builder-ng'...
    error: ca hash mismatch importing path '/nix/store/j3wsx0in5hgnl3sr91i8h19b74w5hcz5-vagrant_cloud-3.0.5.gem';
             specified: sha256:0np0d8rjca130si5iaxasbqmfbbx4l3kd9mxdsa3p5mqiia7za3b
             got:       sha256:14iwaq2d9ai4x36w2vd4gv0zwpa9yj5nv8l6rxqfs5njd69jv90h
    error: builder for '/nix/store/2nwv1fm5bs0a2sgb2a014gv7hgfaj3f7-ruby2.7.4-vagrant_cloud-3.0.5.drv' failed with exit code 1

In contrast to my initial assumption this isn't related to hashing
changes in the CAS-implementation, but actually a problem when using
`nix-prefetch-url(1)` from Nix 2.3 with a daemon from Nix 2.4.

Basically the following happens:

* `nix-prefetch-url` from 2.3 transmits the file to the daemon using
  `wopAddToStore`.
* The daemon (`LocalStore::addToStoreFromDump` to be precise) checks
  whether the entire file can be kept in memory before writing it to the
  disk.

  This happens by writing into a buffer in chunks of 2^16 bytes. If an
  EOF is reached before the buffer exceeds `settings.narBufferSize`, the
  file can be kept in memory entirely.
* When the source is entirely read in, a last iteration will happen
  which results in the EOF. However, in this round the buffer is
  increased by 2^16 bytes again without downsizing it on the EOF (this
  only happens in the rounds without an EOF).
* The result is that the files in the store now have the size
  `(original_size + 2^16)` where the excess bytes are null-bytes at the
  end of the file.
* Because the file has different contents now than computed via the hash
  sink, a hash-mismatch occurs as soon as the file is copied to a remote
  system where the hash is apparently re-validated (in fact I could work
  around the issue from above by declaring `--builders ''`).

Resizing the buffer back to the original size in case of an EOF solves
the problem for me. I also added a regression-test that fails without
the change in `LocalStore::addToStoreFromDump` (in this case the size of
the imported file would be `65542` rather than `6`).

The issue is only observable with a 2.3 `nix-prefetch-url(1)` because
the 2.4 implementation uses `wopAddToStoreNar` which imports paths
slightly different.