libcmd: add missing `<string>` include to `markdown.hh`
Upcoming `gcc-17` cleaned up transitive header inclusion a bit and
exposed missing `nix` header dependency as a build failure:

```
../src/libcmd/include/nix/cmd/markdown.hh:15:6: error: 'string' in namespace 'std' does not name a type
   15 | std::string renderMarkdownToTerminal(std::string_view markdown);
      |      ^~~~~~
../src/libcmd/include/nix/cmd/markdown.hh:5:1: note: 'std::string' is defined in header '<string>'; this is probably fixable by adding '#include <string>'
    4 | #include <string_view>
  +++ |+#include <string>
    5 |
```