libfetchers/git: Allow Git Remote Helpers
Remote helpers are programs that are invoked when Git needs to interact
with remote repositories that it does not support natively, see
<https://git-scm.com/docs/gitremote-helpers>

The following two changes make use of such remote helpers possible in
conjunction with Nix:

  1. Relax URL scheme filtering for the Git fetcher, such that unknown
     URL schemes are not rejected directly.
     In case there is no corresponding remote helper available, the
     following output is produced:

         warning: URL scheme 'git+invalid' is non-standard and requires 'git-remote-invalid'.
         git: 'remote-invalid' is not a git command. See 'git --help'.
         error: program 'git' failed with exit code 128

  2. Add `GIT_DIR` to the environment, since this is required by remote
     helpers.