Check for existing store path in nix profile
Previously, nix profile allowed you to install if they had the same
store path.

For instance, you could do:

$ nix profile install github:nixos/nixpkgs#hello
$ nix profile install nixpkgs#hello

This leads to duplication since multiple elements are the same path.
It could also cause issues when upgrading when two elements have the
same store path at one point, but then diverge later, leading to
conflicts.

The new error message looks like:

  error: Cannot install 'github:nixos/nixpkgs#hello' when its store path (/nix/store/lwl497mzqp0k7cfhh51c948nkagc3bbr-hello-2.10) is already installed through 'github:nixos/nixpkgs#legacyPackages.x86_64-linux.hello'