Fix functionArgs for primops
Both functions and primops have `builtins.typeOf v == "lambda"`, and
they also both return true for `builtins.isFunction`, yet
`builtins.functionArgs` fails for primops without this change:

  $ nix-instantiate --eval -E 'builtins.isFunction builtins.add'
  true

  $ nix-instantiate --eval -E 'builtins.functionArgs builtins.add'
  error: 'functionArgs' requires a function, at (string):1:1

For simplicity, primops aren't assumed to have named function arguments,
which is correct for most of them, so `builtins.functionArgs` now just
returns `{}` for all of them