Error out when flake checks are missing `drvPath`
Previously, we'd silently ignore them, now we treat them as errors.

This `if (drvPath` clause was added in
d12b12a15ba5cda49baacd22fbf7f9f526ed74e4 as part of implementing the
`--keep-going` flag for `nix flake check`.

I noticed this because `buildbot-nix` behaves a bit differently and
tries and fails to build these checks. This is because it uses
`nix-eval-jobs` under the hood, which reports these unbuildable
derivations:

`flake.nix`:

```nix
{
  outputs = _:
    let
      system = "x86_64-linux";
    in
    {
      checks.${system} = {
        missingDrvPath = {
          name = "missing-drvPath";
          type = "derivation";
        };
        anotherMissingDrvPath = {
          name = "another-missing-drvPath";
          type = "derivation";
        };
      };
    };
}
```

```console
$ nix flake show
path:/home/jeremy/tmp/flake-checking?lastModified=1785164239&narHash=sha256-iTBSwIt2gS8PHe4RmkTfh/kewOzaECp9JWLywFpCX20%3D
└───checks
    └───x86_64-linux
        ├───anotherMissingDrvPath: derivation 'another-missing-drvPath'
        └───missingDrvPath: derivation 'missing-drvPath'

$ nix flake check

$ nix run nixpkgs#nix-eval-jobs -- --force-recurse --flake '.#checks'
error: derivation does not contain a 'drvPath' attribute
{"attr":"x86_64-linux.anotherMissingDrvPath","attrPath":["x86_64-linux","anotherMissingDrvPath"],"error":"error: derivation does not contain a 'drvPath' attribute","fatal":false}
error: derivation does not contain a 'drvPath' attribute
{"attr":"x86_64-linux.missingDrvPath","attrPath":["x86_64-linux","missingDrvPath"],"error":"error: derivation does not contain a 'drvPath' attribute","fatal":false}
```