Backwards compatibility hack to handle `/. + path`
This resolves an evaluation error in
https://api.flakehub.com/f/pinned/knightpp/modupdate/0.0.8/018d560c-d88c-7c2b-ba5f-918283ea4c47/source.tar.gz,
which does something like

  filter = path: type:
    builtins.elem (/. + path) [ ./go.mod ... ];

leading to

  error: a string that refers to a store path cannot be appended to a path

The hack is that if we append a virtual path to /., we discard the
orginal accessor and use the one from the right-hand side.