Remove dynamic initialization of base64DecodeChars
Static initialization is simpler and doesn't require any form of
synchronization.

This solves a build error on clang.

    src/libutil/util.cc:1451:30: error: implicit instantiation of undefined template 'std::__1::array<char, 256>'
    static std::array<char, 256> base64DecodeChars;
                             ^
    /nix/store/w6mp8b25lld3b7s0gvi709dfkw619s36-libcxx-7.1.0-dev/include/c++/v1/__tuple:223:64: note: template is declared here
    template <class _Tp, size_t _Size> struct _LIBCPP_TEMPLATE_VIS array;