eval: add `NIX_VALIDATE_EVAL_NONDETERMINISM` know for attrset comparison
This change adds an extra knob to detect nin-determinism in attrset
comparison. It follows real problem discovered by Vladimir Kryachko
in current `nixpkgs` that fails evaluation non-deterministically based
on internal state of the eval:

This works:

    $ nix-instantiate -E 'let pkgs = import <nixpkgs> {}; in pkgs.nix'
    /nix/store/6gzxax0rl0k1n3hg0s22jnj6c1c0aj3b-nix-2.15.1.drv

This fails:

    $ nix-instantiate -E 'let pkgs = import <nixpkgs> {}; in let aaaaaaaaaaa = { bbbbbbbbbbbbbb.extensions = []; }; in pkgs.nix'
    error: assertion '(final).hasSharedLibraries' failed

Note that `let aaaaaaaaaaa = { ... }` binding should not be able to
affect evaluation of `pkgs.nix`.

This happens because attrsets are implementing lazy attrset comparison.
The change implements eager comparison when `NIX_VALIDATE_EVAL_NONDETERMINISM`
is set to ease debugging such failures.