Restore an accidentally suppressed negation
Accidentally removed in ca96f5219489c1002499bfe2c580fdd458219144. This
caused `nix run` to systematically fail with

```
error: app program '/nix/store/…' is not in the Nix store
```