libstore: Make FileTransfer throw Interrupted on interrupted transfers
We are now issuing many more requests in queryMissing concurrently,
without doing checkInterrupt() when enqueueing downloads (arguably we
shouldn't).

The exception ignoring behavior of querySubstitutablePathInfosAsync, where
it swallows and prints exceptions derived from Error & doesn't help - we end
up with a wall of text like:

error: download of 'https://cache.nixos.org/b2s9lqzdi2pg80j0lawgw8ndian3k9mn.narinfo' was interrupted
error: download of 'https://cache.nixos.org/5h2h4brfrgr89gvh1l93mh63mm0h5r6s.narinfo' was interrupted
error: download of 'https://cache.nixos.org/azz5rixma8na4h9s75406w94yjsk2b4k.narinfo' was interrupted
error: download of 'https://cache.nixos.org/xdlfnymy64jxfhnj19sjvdvmbbmyn468.narinfo' was interrupted
error: download of 'https://cache.nixos.org/q8sra2q3n8gvalzbfq48jvv18xjsg2gb.narinfo' was interrupted
error: download of 'https://cache.nixos.org/pzmm2bczb5gb1nvgv5xp6ims9iqcc4af.narinfo' was interrupted
error: download of 'https://cache.nixos.org/s3slcivizcjkppyvf5drlbx0b8dxafg9.narinfo' was interrupted

Rethrowing Interrupted instead of FileTransferError on proper interrupts seems
correct to me. And since it doesn't inherit from Error (but rather BaseError)
it escapes out of catch (Error &) blocks and properly unwinds the stack eagerly.

Also add a new `Cancelled` exception type to reflect cases (not very useful for now)
to indicate that a filetransfer was cancelled without a global interrupt.

In the future we should add per-transfer cancellation mechanisms for this purpose.

(cherry picked from commit 8c9426502817a493d23ce6e112965544fcb21aed)