nix-gc: ignore non-existing links
Before I would get:

finding garbage collector roots...
deleting garbage...
deleting '/nix/store/trash'
deleting unused links...
0 store paths deleted, 0.00 MiB freed
error: getting status of '/nix/store/.links/1gwb16smc3b53iaa5nzfxjypys4pl32liw59aw01zvfjpaz53wg': No such file or directory