libexpr: Handle lazy paths in builtins.storePath better
When building nix.dev manual I ran into an issue with the current
handling of lazy paths:

    … while calling the 'import' builtin
     at /nix/store/8kpx53qi52yhjai1vdw8zpa95iqa61bv-source/default.nix:167:19:
      166|
      167|           flake = import (outPath + "/flake.nix");
         |                   ^
      168|

   … while realising the context of a path

   … while calling the 'storePath' builtin
     at /nix/store/8kpx53qi52yhjai1vdw8zpa95iqa61bv-source/default.nix:115:15:
      114|               # If it's already a store path, don't copy it again.
      115|               builtins.storePath src
         |               ^
      116|             else

    error: path '/nix/store/5fn5lshxlh5zb8w1a747apqlqlbi3j0x-source' is required, but there is no substituter that can build it

This also has the benefit of not relying on nix::canonPath(), which is one of the bits of I/O not funneled through the rootFS accessor.

The responsible code is in flake-compat [1]. With a path we lack the correct context but it points to a "lazy" path in the store.
Funneling I/O into the accessor seems like the correct solution here.

[1]: https://github.com/NixOS/flake-compat/blob/5edf11c44bc78a0d334f6334cdaf7d60d732daab/default.nix#L147-L156

(cherry picked from commit 933f3140b1e73de2b909902b0e251c7da4031607)