Fix empty "error:" message when a top-level goal is never built
E.g.

  # nix build --store /tmp/nix --file tests/ca/content-addressed.nix
  error: builder for '/nix/store/da7d4sy5lmppl9a173hc8h00xd8vbng6-simple-input-addressed.drv' failed with exit code 1;
         last 1 log lines:
         > error: executing '/nix/store/dsd5gz46hdbdk2rfdimqddhq6m8m8fqs-bash-5.1-p16/bin/bash': No such file or directory
         For full logs, run 'nix log /nix/store/da7d4sy5lmppl9a173hc8h00xd8vbng6-simple-input-addressed.drv'.
  error:

This is because the file contains multiple goals, one of which fails,
and the others are never built because of that, and therefore have
status MiscFailure and an empty errorMsg.

This introduces an "abandoned" status and sets errorMsg accordingly.