Throw CachedEvalError if a cached value exists but has type "failed"
Otherwise you get unhelpful errors like

  error: 'apps' is not an attribute set

Fixes #12762.

(cherry picked from commit 8b438fccb4fce1e8c06136ff9f9bae324911c193)