libstore/machines: catch `stoull`-error and provide a better error message
Quite recently I got the order of arguments wrong while doing a
remote-build with `nix-build --builders` that resulted in the following,
rather unhelpful error:

    $ nix-build -A grafana -j0 \
        --option builders 'ssh://ma27@builder x86_64-linux 32 32 big-parallel'
    error: stoull
    error: unexpected EOF reading a line
    (use '--show-trace' to show detailed location information)

This is because I forgot that argument `3' is supposed to be the SSH key
and thus the speed-factor was `big-parallel`. I decided to wrap the
calls to `std::stoull` and provide a more meaningful error if this
happens:

    error: Cannot stoull 'big-parallel'! Argument '5' is supposed to be a 'speed factor'!
    error: unexpected EOF reading a line