libstore: handle root path in RemoteFSAccessor::maybeLstat
RemoteFSAccessor::fetch() crashes when called with the root path.

  $ nix build nixpkgs#hello --store ssh-ng://host
  error: path '/nix/store/' is not in the Nix store

Add path.isRoot() guard like LocalStoreAccessor::maybeLstat

Fixes: eb643d034 ("`Store::getFSAccessor`: Do not include the store dir")
(cherry picked from commit b523564eb3b5ec5070d5de82d19906a06726c9ea)