gc: skip the processes own pid
fixes manually deleting paths

nix store delete /nix/store/...-zlib-1.2.11-static
error: Cannot delete path '/nix/store/...-zlib-1.2.11-static' since it is still alive. To find out why, use: nix-store --query --roots

it failed due to the function finding itself using that path