Denote empty files in stack traces
Instead of

  error: syntax error, unexpected end of file
  at «git+file:///.../nixos?rev=0defd19d32413f757d7273596cd9641cb91af25a&shallow=1&submodules=1»/configuration.nix:1:1:

Nix now shows

  error: syntax error, unexpected end of file
  at «git+file:///home/eelco/Dev/nix-master/nixos?rev=0defd19d32413f757d7273596cd9641cb91af25a&shallow=1&submodules=1»/configuration.nix:1:1:
      1| (empty file)