Daemon: Ignore interrupts between accept() and child start
Sending SIGINT to the nix-daemon parent process is supposed to stop
the parent, not the children. So any connection that has been
accept()ed should continue normally. However, there is a time window
between the call to accept() and the fork() of the child where we
could receive SIGINT, which would cause the child to throw an
"Interrupted" exception. This shows up in the client as

  error: cannot open connection to remote store 'daemon': read of 32768 bytes: Connection reset by peer

Solution: don't call checkInterrupts() after accept(), and clear the
interrupt flag in the child process.