nix flake pin: Mark the resulting registry entry as exact
Since the resulting target flakeref contains attributes like
"lastModified" or "narHash", it's not suitable for overriding. This
led to errors like

  $ nix build nixpkgs/24.05#hello
  error: 'lastModified' attribute mismatch in input 'github:NixOS/nixpkgs/63dacb46bf939521bdc93981b4cbb7ecb58427a0', expected 1728538411, got 1717179513

after doing `nix registry pin nixpkgs`.